DROP TABLE IF EXISTS Test
DROP TABLE IF EXISTS User
CREATE TABLE Test
(
  Id       SMALLSERIAL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255)  NOT NULL,
  CONSTRAINT TestPK PRIMARY KEY (Id)
);
CREATE TABLE User
(
  Id       SMALLSERIAL,
  userName VARCHAR(255) NOT NULL,
  password VARCHAR(255)  NOT NULL,
  role VARCHAR(255)  NOT NULL,
  CONSTRAINT UserPK PRIMARY KEY (Id)
);